#include <iostream>
#include <csignal>
#include <unistd.h>

#include "LEDStripController.h"
#include "LEDStripControllerRpi3.h"

#define LED_COUNT   74

volatile sig_atomic_t keep_running = 1;

void signal_handler(int signal) {
    keep_running = 0;
}

int main()
{
    LEDStripController* controller;
    int 
    controller = new LEDStripControllerRpi3(LED_COUNT);

    controller->init();
    
    // Register signal handler for Ctrl + C
    // SIGINT generated by Ctrl + C
    std::signal(SIGINT, signal_handler);

    while (keep_running) {
        controller->render();
        usleep(1000000 / 15); // 15 frames per second
    }

    std::cout << "Exiting program." << std::endl;
    return 0;
    
    
    
    
    
    //controller->clear();
    //controller->render();

}
